I0209 04:43:00.001907       1 main.go:31] Starting ccm with CIVO_API_URL: https://api.civo.com, CIVO_REGION: lon1, CIVO_CLUSTER_ID: 1f49054e-1263-43a7-b7fb-2ea1c0f24d89
I0209 04:43:00.551417       1 serving.go:347] Generated self-signed cert in-memory
W0209 04:43:00.779239       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0209 04:43:00.783421       1 controllermanager.go:142] Version: v0.0.0-master+$Format:%H$
I0209 04:43:00.790461       1 secure_serving.go:197] Serving securely on [::]:10258
I0209 04:43:00.792426       1 leaderelection.go:243] attempting to acquire leader lease kube-system/cloud-controller-manager...
I0209 04:43:00.793128       1 requestheader_controller.go:169] Starting RequestHeaderAuthRequestController
I0209 04:43:00.793351       1 shared_informer.go:240] Waiting for caches to sync for RequestHeaderAuthRequestController
I0209 04:43:00.793557       1 tlsconfig.go:240] Starting DynamicServingCertificateController
I0209 04:43:00.793867       1 configmap_cafile_content.go:202] Starting client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0209 04:43:00.794028       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0209 04:43:00.794284       1 configmap_cafile_content.go:202] Starting client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0209 04:43:00.794443       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0209 04:43:00.821160       1 leaderelection.go:253] successfully acquired lease kube-system/cloud-controller-manager
I0209 04:43:00.823179       1 event.go:291] "Event occurred" object="kube-system/cloud-controller-manager" kind="Lease" apiVersion="coordination.k8s.io/v1" type="Normal" reason="LeaderElection" message="k3s-demo2-db61-ddc4c9-node-pool-28ad_be6e3df7-24e7-4d83-a191-114b585db566 became leader"
I0209 04:43:00.893998       1 shared_informer.go:247] Caches are synced for RequestHeaderAuthRequestController 
I0209 04:43:00.894348       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file 
I0209 04:43:00.894625       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file 
I0209 04:43:02.585618       1 request.go:668] Waited for 1.046399543s due to client-side throttling, not priority and fairness, request: GET:https://10.43.0.1:443/apis/extensions/v1beta1?timeout=32s
E0209 04:43:03.541272       1 controllermanager.go:418] unable to get all supported resources from server: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
W0209 04:43:03.545322       1 core.go:110] --configure-cloud-routes is set, but cloud provider does not support routes. Will not configure cloud provider routes.
W0209 04:43:03.545771       1 controllermanager.go:282] Skipping "route"
I0209 04:43:03.548911       1 node_controller.go:115] Sending events to api server.
I0209 04:43:03.549569       1 controllermanager.go:285] Started "cloud-node"
I0209 04:43:03.552697       1 node_lifecycle_controller.go:76] Sending events to api server
I0209 04:43:03.553052       1 controllermanager.go:285] Started "cloud-node-lifecycle"
I0209 04:43:03.555272       1 controllermanager.go:285] Started "service"
I0209 04:43:03.555903       1 node_controller.go:154] Waiting for informer caches to sync
I0209 04:43:03.556201       1 controller.go:230] Starting service controller
I0209 04:43:03.556295       1 shared_informer.go:240] Waiting for caches to sync for service
I0209 04:43:03.656559       1 shared_informer.go:247] Caches are synced for service 
I0209 04:43:03.656743       1 node_controller.go:390] Initializing node k3s-demo2-db61-ddc4c9-node-pool-52a9 with cloud provider
E0209 04:43:03.664317       1 instances.go:52] Unable to get instance by provider id: , error: instance not found
E0209 04:43:04.304573       1 instances.go:52] Unable to get instance by provider id: , error: instance not found
I0209 04:43:05.587367       1 node_controller.go:454] Successfully initialized node k3s-demo2-db61-ddc4c9-node-pool-52a9 with cloud provider
I0209 04:43:05.587522       1 node_controller.go:390] Initializing node k3s-demo2-db61-ddc4c9-node-pool-28ad with cloud provider
I0209 04:43:05.588542       1 event.go:291] "Event occurred" object="k3s-demo2-db61-ddc4c9-node-pool-52a9" kind="Node" apiVersion="v1" type="Normal" reason="Synced" message="Node synced successfully"
I0209 04:43:07.642612       1 node_controller.go:454] Successfully initialized node k3s-demo2-db61-ddc4c9-node-pool-28ad with cloud provider
I0209 04:43:07.643808       1 event.go:291] "Event occurred" object="k3s-demo2-db61-ddc4c9-node-pool-28ad" kind="Node" apiVersion="v1" type="Normal" reason="Synced" message="Node synced successfully"
I0209 04:43:16.150839       1 node_controller.go:390] Initializing node k3s-demo2-db61-ddc4c9-node-pool-c02b with cloud provider
I0209 04:43:17.973838       1 node_controller.go:454] Successfully initialized node k3s-demo2-db61-ddc4c9-node-pool-c02b with cloud provider
I0209 04:43:17.974031       1 node_controller.go:390] Initializing node k3s-demo2-db61-ddc4c9-node-pool-c02b with cloud provider
I0209 04:43:17.977859       1 event.go:291] "Event occurred" object="k3s-demo2-db61-ddc4c9-node-pool-c02b" kind="Node" apiVersion="v1" type="Normal" reason="Synced" message="Node synced successfully"
I0209 04:43:19.838101       1 node_controller.go:454] Successfully initialized node k3s-demo2-db61-ddc4c9-node-pool-c02b with cloud provider
I0209 04:43:19.841521       1 event.go:291] "Event occurred" object="k3s-demo2-db61-ddc4c9-node-pool-c02b" kind="Node" apiVersion="v1" type="Normal" reason="Synced" message="Node synced successfully"
I0209 04:43:38.938875       1 event.go:291] "Event occurred" object="kube-system/traefik" kind="Service" apiVersion="v1" type="Normal" reason="EnsuringLoadBalancer" message="Ensuring load balancer"
I0209 04:43:39.115887       1 event.go:291] "Event occurred" object="kube-system/traefik" kind="Service" apiVersion="v1" type="Normal" reason="EnsuredLoadBalancer" message="Ensured load balancer"
I0209 04:43:39.127594       1 event.go:291] "Event occurred" object="kube-system/traefik" kind="Service" apiVersion="v1" type="Normal" reason="EnsuringLoadBalancer" message="Ensuring load balancer"
I0209 04:43:39.240188       1 event.go:291] "Event occurred" object="kube-system/traefik" kind="Service" apiVersion="v1" type="Normal" reason="EnsuredLoadBalancer" message="Ensured load balancer"
I0209 04:53:16.535875       1 event.go:291] "Event occurred" object="default/nginx2" kind="Service" apiVersion="v1" type="Normal" reason="EnsuringLoadBalancer" message="Ensuring load balancer"
E0209 04:53:18.100239       1 loadbalancer.go:135] Loadbalancer is not available, state: pending_cm_creation
E0209 04:53:18.100349       1 controller.go:307] error processing service default/nginx2 (will retry): failed to ensure load balancer: loadbalancer is not yet available, current state: pending_cm_creation
I0209 04:53:18.101857       1 event.go:291] "Event occurred" object="default/nginx2" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to ensure load balancer: loadbalancer is not yet available, current state: pending_cm_creation"
I0209 04:53:18.102191       1 event.go:291] "Event occurred" object="default/nginx2" kind="Service" apiVersion="v1" type="Normal" reason="EnsuringLoadBalancer" message="Ensuring load balancer"
I0209 04:53:18.643491       1 event.go:291] "Event occurred" object="default/nginx2" kind="Service" apiVersion="v1" type="Normal" reason="EnsuredLoadBalancer" message="Ensured load balancer"
I0209 04:53:23.101916       1 event.go:291] "Event occurred" object="default/nginx2" kind="Service" apiVersion="v1" type="Normal" reason="EnsuringLoadBalancer" message="Ensuring load balancer"
I0209 04:53:23.631090       1 event.go:291] "Event occurred" object="default/nginx2" kind="Service" apiVersion="v1" type="Normal" reason="EnsuredLoadBalancer" message="Ensured load balancer"
I0209 05:05:23.440040       1 event.go:291] "Event occurred" object="shipa-system/shipa-ingress-nginx" kind="Service" apiVersion="v1" type="Normal" reason="EnsuringLoadBalancer" message="Ensuring load balancer"
E0209 05:05:25.050658       1 loadbalancer.go:135] Loadbalancer is not available, state: 
E0209 05:05:25.050825       1 controller.go:307] error processing service shipa-system/shipa-ingress-nginx (will retry): failed to ensure load balancer: loadbalancer is not yet available, current state: 
I0209 05:05:25.051910       1 event.go:291] "Event occurred" object="shipa-system/shipa-ingress-nginx" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to ensure load balancer: loadbalancer is not yet available, current state: "
I0209 05:05:25.052063       1 event.go:291] "Event occurred" object="shipa-system/shipa-ingress-nginx" kind="Service" apiVersion="v1" type="Normal" reason="EnsuringLoadBalancer" message="Ensuring load balancer"
I0209 05:05:25.762881       1 event.go:291] "Event occurred" object="shipa-system/shipa-ingress-nginx" kind="Service" apiVersion="v1" type="Normal" reason="EnsuredLoadBalancer" message="Ensured load balancer"
I0209 05:05:30.052098       1 event.go:291] "Event occurred" object="shipa-system/shipa-ingress-nginx" kind="Service" apiVersion="v1" type="Normal" reason="EnsuringLoadBalancer" message="Ensuring load balancer"
I0209 05:05:30.596894       1 event.go:291] "Event occurred" object="shipa-system/shipa-ingress-nginx" kind="Service" apiVersion="v1" type="Normal" reason="EnsuredLoadBalancer" message="Ensured load balancer"
